collections:
  - name: kubernetes.core
    version: 2.3.2
    source: https://galaxy.ansible.com

  - name: ansible.controller
    version: 4.2.0
    source: https://console.redhat.com/api/automation-hub/
