apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-lint
  namespace: ansible-pipeline
spec:
  description: "Run ansible lint on repository"
  steps:
    - image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - -c
        - echo "Hello World"
