kind: Secret
apiVersion: v1
metadata:
  name: ansible-staging-gitcredentials
type: Opaque
stringData:
  .gitconfig: |
    [credential "https//gitea-http.gitea.svc.cluster.local"]
      helper = store
  .git-credentials: |
    https://developer:652m89ni@gitea-http.gitea.svc.cluster.local
