apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-staging
  namespace: ansible-pipeline
spec:
  workspaces:
    - name: ansible-lint-ws
    - name: gitcredentials-ws
  tasks:
    - name: git-clone
      params:
        - name: url
          value: http://gitea-http.gitea:3000/developer/ansible-example-collection.git
        - name: revision
          value: main
        - name: depth
          value: "0"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: ansible-lint-ws
        - name: basic-auth
          workspace: gitcredentials-ws
    - name: ansible-lint
      taskRef:
        name: ansible-lint
      workspaces:
        - name: output
          workspace: ansible-lint-ws
      runAfter:
        - git-clone
    - name: git-merge
      taskRef:
        name: git-merge
      workspaces:
        - name: output
          workspace: ansible-lint-ws
      runAfter:
        - ansible-lint
