apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-lint
  namespace: ansible-pipeline
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    Run ansible lint on repository.
  workspaces:
    - name: output
      description: Directory containing a the ansible files to be linted
  steps:
    - name: lint
      image: quay.io/ansible/creator-ee:v0.6.0
      env:
      - name: WORKSPACE_OUTPUT_PATH
        value: $(workspaces.output.path)
      script: |
        #!/usr/bin/env sh

        set -eu -o pipefail

        /usr/local/bin/ansible-lint --version

        /usr/local/bin/ansible-lint --project-dir $WORKSPACE_OUTPUT_PATH
