apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-lint
  namespace: ansible-pipeline
spec:
  description: "Run ansible lint on repository"
  steps:
    - image: quay.io/ansible/creator-ee:v0.6.0
      command:
        - /usr/local/bin/ansible-lint
        - --version
