apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ansible-staging
  namespace: ansible-pipeline
spec:
  params:
    - name: git-repository-url
      description: The git repository url
    - name: git-ref
      description: The ref that triggered this run
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ansible-staging-
      spec:
        pipelineRef:
          name: ansible-staging
        params:
          - name: repository
            value: $(tt.params.git-repository-url)
          - name: before
            value: $(tt.params.git-revision.before)
          - name: after
            value: $(tt.params.git-revision.after)
          - name: ref
            value: $(tt.params.git-ref)
