apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: feature-environment
  namespace: ansible-pipeline
spec:
  params:
    - name: git-repository-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: feature-environment-
      spec:
        pipelineRef:
          name: feature-environment
        params:
          - name: repository
            value: $(tt.params.git-repository-url)
          - name: before
            value: $(tt.params.git-revision.before)
          - name: after
            value: $(tt.params.git-revision.after)
          - name: ref
            value: $(tt.params.git-ref)
