kind: Secret
apiVersion: v1
metadata:
  name: gitea-clone
type: Opaque
stringData:
  .gitconfig: |
    [credential "https//gitea-http.gitea.svc.cluster.local"]
      helper = store
  .git-credentials: |
    https://admin:test123@gitea-http.gitea.svc.cluster.local
