apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ansible-stating-
spec:
  pipelineRef:
    name: ansible-staging
  # params:
  #   - name: repository
  #     value: $(tt.params.git-repository-url)
  workspaces:
    - name: ansible-lint-ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Mi
    - name: gitcredentials-ws
      secret:
        secretName: ansible-staging-gitcredentials
