---
- name: Get cluster base domain for Automation Controller
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
  register: controller_ocp_ingress_config

- name: Print ingress domain
  ansible.builtin.debug:
    var: controller_ocp_ingress_config
    verbosity: 2

- name: Register fact with for the Controller domain
  ansible.builtin.set_fact:
    controller_domain: "{{ controller_ocp_ingress_config.resources[0].spec.domain }}"

- name: Print controller_domain variable
  ansible.builtin.debug:
    var: controller_domain
    verbosity: 2

- name: Create namespace for Ansible platform operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          openshift.io/cluster-monitoring: "true"
        name: ansible-automation-platform

- name: Create OperatorGroup for Ansible platform operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: ansible-automation-platform-operator
        namespace: ansible-automation-platform
      spec:
        targetNamespaces:
        - ansible-automation-platform

- name: Create Subscription for the Ansible platform operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: ansible-automation-platform-operator
        namespace: ansible-automation-platform
      spec:
        channel: stable-2.2
        installPlanApproval: Automatic
        name: ansible-automation-platform-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

# Stolen from https://stackoverflow.com/questions/53198576/ansible-playbook-wait-until-all-pods-running
- name: Wait for Ansible platform operator pods to be running
  ansible.builtin.shell: kubectl get pods -o json -n ansible-automation-platform
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 5

- name: Check if we have an aws gp2-csi storage class available
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: gp2-csi
  register: controller_gp2_csi_storageclass

- name: Print controller_gp2_csi_storageclass
  ansible.builtin.debug:
    var: controller_gp2_csi_storageclass
    verbosity: 2

- name: Overwrite default storageclass if gp2-csi is available
  ansible.builtin.set_fact:
    controller_storageclass: gp2-csi
  when: controller_gp2_csi_storageclass.resources[0] is defined

- name: Print controller_storageclass
  ansible.builtin.debug:
    var: controller_storageclass
    verbosity: 2

- name: Deploy AutomationController
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: automationcontroller.ansible.com/v1beta1
      kind: AutomationController
      metadata:
        labels:
        name: ctrl
        namespace: ansible-automation-platform
      spec:
        admin_user: admin
        create_preload_data: true
        garbage_collect_secrets: false
        image_pull_policy: IfNotPresent
        ingress_type: route
        loadbalancer_port: 80
        loadbalancer_protocol: http
        nodeport_port: 30080
        postgres_storage_class: "{{ controller_storageclass }}"
        postgres_storage_requirements:
          requests:
            storage: 8Gi
        projects_persistence: false
        projects_storage_access_mode: ReadWriteMany
        projects_storage_size: 5Gi
        replicas: 1
        route_host: "ctrl.{{ controller_domain }}"
        route_tls_termination_mechanism: Edge
        service_type: ClusterIP
        task_privileged: false

- name: Wait for all Ansible platform pods to be running
  ansible.builtin.shell: kubectl get pods -o json -n ansible-automation-platform -l app.kubernetes.io/part-of=ctrl
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]

- name: Get Automation Controller admin credentials
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: ctrl-admin-password
    namespace: ansible-automation-platform
  register: controller_password_secret

- name: Get Controller URL from OpenShift
  community.kubernetes.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: ctrl
    namespace: ansible-automation-platform
  register: controller_route

- name: Register fact with controller password
  ansible.builtin.set_fact:
    controller_password: "{{ controller_password_secret.resources[0].data.password | b64decode }}"
    controller_url: "https://{{ controller_route.resources[0].spec.host }}"

- name: Give the controller time to start
  ansible.builtin.uri:
    url: "{{ controller_url }}/api/v2/ping/"
    validate_certs: no
  register: result
  until: "result.status == 200"
  retries: 6
  delay: 10

- name: Disable SSL verification for GIT in controller
  ansible.controller.settings:
    name: AWX_TASK_ENV
    value:
      GIT_SSL_NO_VERIFY: "True"
      HOME: "/var/lib/awx"
    # controller variables
    controller_username: admin
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_url }}"
    validate_certs: no
