#
# On monday we install automation controller
#
# This also defines some basic facts for connecting to the controller
# - controller_url
# - controller_password
#
- include_tasks: install.yml

#
# Check the state of the subscription
#
# This will fail if no subscription is available
#
- include_tasks: subscription.yml

#
# First we need a authentication token
#
- include_tasks: token.yml

#
# Now we can add all required content
#
# - Projects
# - Job Templates
#
- include_tasks: content.yml
  when: controller_subscription_installed
