---
#
# On monday we install automation controller
#
# This also defines some basic facts for connecting to the controller
# - controller_url
# - controller_password
#
- name: Install Ansible Controller
  ansible.builtin.include_tasks: install.yml

# On Tuesday we check the state of the subscription
#
# This will fail if no subscription is available
#
- name: Check for a subscriptions
  ansible.builtin.include_tasks: subscription.yml

# On Wednesday we create an authentication token
#
- name: Create authentication token
  ansible.builtin.include_tasks: token.yml

# On Thursday we add all required content
#
# - Projects
# - Job Templates
#
- name: Create required Ansible Controller content
  ansible.builtin.include_tasks: content.yml
  when: controller_subscription_installed
