- name: Add Gitea helm repository
  kubernetes.core.helm_repository:
    name: gitea
    repo_url: https://dl.gitea.io/charts/

- name: Create gitea namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ gitea_namespace}}"

# The gitea image uses a fixed UID, leverage the nonroot scc
- name: Allow default service account to use nonroot scc
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: gitea-nonroot
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:nonroot
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: gitea

- name: Install Gitea via helm
  kubernetes.core.helm:
    name: gitea
    release_namespace: "{{ gitea_namespace }}"
    chart_ref: gitea/gitea
    chart_version: v6.0.0
    values:
      gitea:
        config:
          server:
            ROOT_URL: https://gitea.apps.ocp.lan.stderr.at
          webhook:
            ALLOWED_HOST_LIST: private
      image:
        rootless: true
      # securityContext:
      #     capabilities:
      #       add: ["SYS_CHROOT"]
      postgresql:
        enabled: true
      memcached:
        enabled: false

- name: Create OpenShift route
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        labels:
          app: gitea
        name: gitea-https
        namespace: "{{ gitea_namespace }}"
      spec:
        host: gitea.apps.ocp.lan.stderr.at
        port:
          targetPort: http
        to:
          kind: Service
          name: gitea-http
          weight: 100
        wildcardPolicy: None
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect

- name: Wait for gitea pods to be running
  shell: kubectl get pods -o json -n gitea
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 5
