---
- ansible.builtin.include_tasks: install.yml
  when: not gitea_skip_gitea | bool

# The Gitea URL is also used in the controller role
- name: Get Gitea URL from OpenShift
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: gitea-https
    namespace: "{{ gitea_namespace }}"
  register: gitea_route

- name: Create fact for the route URL
  ansible.builtin.set_fact:
    gitea_url: "https://{{ gitea_route.resources[0].spec.host }}"

- ansible.builtin.include_tasks: content.yml
  when: not gitea_skip_gitea | bool
