apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-staging
  namespace: ansible-pipeline
spec:
  workspaces:
    - name: ansible-lint-ws
    - name: git-credentials-ws
  params:
    - name: repository
      type: string
      description: The URL to the repository
      default: http://does-not-exist
  tasks:
    - name: git-clone
      params:
        - name: url
          # temp use fixed url to repo, the public url (route) uses a tmp certificate
          value: http://gitea-http.gitea:3000/developer/ansible-example-collection.git
          # value: "$(params.repository)"
        - name: revision
          value: main
        - name: depth
          value: "0"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: ansible-lint-ws
        - name: basic-auth
          workspace: git-credentials-ws

    - name: ansible-lint
      taskRef:
        name: ansible-lint
      workspaces:
        - name: output
          workspace: ansible-lint-ws
      runAfter:
        - git-clone

    - name: run-molecule
      taskRef:
        name: ansible-molecule
      workspaces:
        - name: output
          workspace: ansible-lint-ws
      runAfter:
        - ansible-lint

    - name: merge-to-dev
      taskRef:
        name: git-merge
      workspaces:
        - name: output
          workspace: ansible-lint-ws
        - name: basic-auth
          workspace: git-credentials-ws
      runAfter:
        - run-molecule

    - name: deploy-to-dev
      params:
        - name: controller-url
          value: http://ctrl-service.ansible-automation-platform
        - name: controller-job-name
          value: "Pipeline - SOE - Development hosts"
      taskRef:
        name: controller-job
      runAfter:
        - merge-to-dev

    - name: pull-request-to-prod
      params:
        - name: sourceBranch
          value: development
        - name: destinationBranch
          value: production
      taskRef:
        name: pull-request
      runAfter:
        - deploy-to-dev
