apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ansible-feature
  namespace: ansible-pipeline
spec:
  workspaces:
    - name: ansible-lint-ws
    - name: git-credentials-ws
  params:
    - name: repository
      type: string
      description: The URL to the repository
      default: http://does-not-exist
    - name: ref
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          # value: "$(params.repository)"
          # temp use fixed url to repo, the public url (route) uses a tmp certificate
          value: http://gitea-http.gitea:3000/developer/ansible-example-collection.git
        - name: revision
          value: $(params.ref)
        - name: depth
          value: "0"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: ansible-lint-ws
        - name: basic-auth
          workspace: git-credentials-ws
    - name: ansible-lint
      taskRef:
        name: ansible-lint
      workspaces:
        - name: output
          workspace: ansible-lint-ws
      runAfter:
        - git-clone
    - name: create-merge-request
      params:
        - name: head
          value: $(params.ref)
      taskRef:
        name: create-merge-request
      workspaces:
        - name: basic-auth
          workspace: git-credentials-ws
      runAfter:
        - ansible-lint
