apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ansible-merge-feature
  namespace: ansible-pipeline
spec:
  serviceAccountName: pipeline
  triggers:

    - name: trigger
      bindings:
        - ref: ansible-merge-triggerbinding
      template:
        ref: ansible-merge-feature
