apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ansible-merge-triggerbinding
  namespace: ansible-pipeline
spec:
  params:
    - name: git-revision-before
      value: $(body)
    - name: git-revision-after
      value: $(body)
    - name: git-ref
      value: $(body.ref)
    - name: git-repository-url
      value: $(body.repository.clone_url)
