- name: Query Gitea webhook
  ansible.builtin.uri:
    url: "{{ gitea_url}}/api/v1/repos/developer/ansible-example-collection/hooks"
    user: "{{ gitea_username }}"
    password: "{{ gitea_developer_password }}"
    force_basic_auth: yes
    method: GET
    validate_certs: no
  register: integration_gitea_webhook_query

- name: Register fact with all Gitea web hooks
  set_fact:
    hook_urls: "{{ integration_gitea_webhook_query.json | json_query('[*].config.url') | join(' | ')}}"

- name: Register fact if specific hooks are defined
  ansible.builtin.set_fact:
    integration_gitea_webhook_pipeline_defined: "{{ hook_urls | regex_search('el-ansible-staging-ansible-pipeline') is not none }}"
    integration_gitea_webhook_controller_defined: "{{ hook_urls | regex_search('ctrl-service') is not none }}"

- name: Print state of defined webhooks
  debug:
    msg:
      - "Webhook to trigger controller feature environment job is defined? {{ integration_gitea_webhook_controller_defined }}"
      - "Webhook to trigger tekton pipeline is defined? {{ integration_gitea_webhook_pipeline_defined }}"

- name: Query controller for webhook key
  ansible.builtin.uri:
    url: "{{ controller_url }}/api/v2/job_templates/Pipeline%20-%20Gitea%20Webhook++Pipeline/webhook_key/"
    method: GET
    user: admin
    password: "{{ controller_password }}"
    method: GET
    force_basic_auth: yes
    validate_certs: no
  register: integration_controller_webhook_key_query

- name: Register fact with webhook key
  ansible.builtin.set_fact:
    integration_controller_webhook_key: "{{ integration_controller_webhook_key_query.json.webhook_key }}"

- name: Create Webhook to trigger Ansible Controller Job for creating feature environments
  ansible.builtin.uri:
    url: "{{ gitea_url}}/api/v1/repos/developer/ansible-example-collection/hooks"
    user: "{{ gitea_username }}"
    password: "{{ gitea_developer_password }}"
    force_basic_auth: yes
    method: POST
    status_code:
      - 201
    body_format: json
    body: "{{ lookup('ansible.builtin.template','gitea-controller-webhook.json.j2') }}"
    validate_certs: no
  when:
    - not integration_gitea_webhook_controller_defined

- name: Create Webhook to trigger Tekton pipline
  ansible.builtin.uri:
    url: "{{ gitea_url}}/api/v1/repos/developer/ansible-example-collection/hooks"
    user: "{{ gitea_username }}"
    password: "{{ gitea_developer_password }}"
    force_basic_auth: yes
    method: POST
    status_code:
      - 201
    body_format: json
    body: "{{ lookup('ansible.builtin.template','gitea-tekton-webhook.json.j2') }}"
    validate_certs: no
  when:
    - not integration_gitea_webhook_pipeline_defined
