- name: Read the developer token from the corresponding K8s secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: gitea-developer-token
    namespace: "{{ gitea_namespace }}"
  register: integration_gitea_developer_token_secret

- name: Register fact integration_gitea_developer_token
  ansible.builtin.set_fact:
    integration_gitea_developer_token: "{{ integration_gitea_developer_token_secret.resources[0].data.token | b64decode}}"

- name: Store the developer token in a Kubernetes secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitea-developer-token
        namespace: "{{ integration_pipeline_namespace }}"
      data:
        token: "{{ integration_gitea_developer_token | b64encode }}"
