- name: Prepare required content for the pipelines demo
  hosts: localhost
  tasks:
    - name: Create temporary checkout directory
      ansible.builtin.tempfile:
        state: directory
        suffix: checkout
      register: checkout_dir

    - name: Clone example Ansible code repository to tmp folder
      ansible.builtin.git:
        repo: https://github.com/rhatservices/ansible-example-collection
        dest: "{{ checkout_dir.path }}"
        version: main

    - name: Get Gitea URL from OpenShift
      community.kubernetes.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: gitea-https
        namespace: gitea
      register: gitea_info

    - name: Store Gitea route in variable
      ansible.builtin.set_fact:
        gitea_route: "https://{{ gitea_info.resources[0].spec.host }}"
        gitea_route_auth: "https://tosmi:test123@{{ gitea_info.resources[0].spec.host }}"

    - name: Create remote Gitea repository
      ansible.builtin.uri:
        url: "{{ gitea_route}}/api/v1/user/repos"
        user: tosmi
        password: test123
        force_basic_auth: yes
        method: POST
        status_code:
          - 201
          - 409
        body_format: json
        body: "{{ lookup('ansible.builtin.file','gitea-repo.json') }}"
        validate_certs: no

    - name: Add Gitea as a new remote
      ansible.builtin.command: git -c http.sslVerify=false remote add gitea "{{ gitea_route_auth }}/tosmi/ansible-example-collection.git"
      args:
        chdir: "{{ checkout_dir.path }}"

    - name: Push repo to gitea
      ansible.builtin.command: git -c http.sslVerify=false push --all gitea
      args:
        chdir: "{{ checkout_dir.path }}"

    - name: Delete temporary checkout directory
      ansible.builtin.file:
        state: absent
        path: "{{ checkout_dir.path }}"
      when: checkout_dir.path is defined
