---
- name: Reset Gitea installation and make sure everything else works
  hosts: localhost
  vars:
    gitea_helm_version: v9.4.0
    aap_operator_channel: stable-2.4
  roles:
    # Keep the order here!
    # It's also defined in meta/main.yml
    - gitea
    - pipeline
    - controller
    - integration

  pre_tasks:
    - ansible.builtin.include_role:
        name: gitea
        tasks_from: uninstall.yaml
