- name: Setup local cluster
  hosts: localhost
  roles:
    - gitea
    - pipeline
    - controller
  post_tasks:
    - name: Print gitea user credentials if newly registered
      ansible.builtin.debug:
        msg:
          - "Gitea user: {{ gitea_username }}"
          - "Gitea user: {{ gitea_password }}"
          - "Gitea URL : {{ gitea_url }}"
      when:
        - not gitea_skip_gitea | bool
        - not gitea_user_registered | bool

    - name: Print Ansible Controller information
      ansible.builtin.debug:
        msg:
        - "Ansible Controller user    : admin"
        - "Ansible Controller password: {{ controller_password }}"
        - "Ansible Controller URL     : {{ controller_url }}"
        - ""
        - "Go to {{ controller_url }} and add a subscription!"
        - "After adding the subscription execute 'make controller-content"
      when:
        - controller_url is defined
        - not controller_subscription_installed | bool
