- name: Setup local cluster
  hosts: localhost
  roles:
    # Keep the order here!
    # It's also defined in meta/main.yml
    - gitea
    - pipeline
    - controller
    - integration

  post_tasks:
    - name: Print gitea user credentials if newly registered
      ansible.builtin.debug:
        msg:
          - "Gitea user: {{ gitea_username }}"
          - "Gitea password: {{ gitea_developer_password }}"
          - "Gitea token: {{ gitea_developer_token }}"
          - "Gitea URL : {{ gitea_url }}"
      when:
        - not gitea_skip_gitea | bool

    - name: Print Ansible Controller information
      ansible.builtin.debug:
        msg:
        - "Ansible Controller user    : admin"
        - "Ansible Controller password: {{ controller_password }}"
        - "Ansible Controller URL     : {{ controller_url }}"
        - "Ansible Controller Token   : {{ controller_oauthtoken | default('Undefined: add a subscription') }}"
      when:
        - controller_url is defined

    - name: Remember user to add an Ansible Controller subscriptions
      ansible.builtin.debug:
        msg:
        - "Go to {{ controller_url }} and add a subscription!"
        - "After adding the subscription execute 'make controller-content"
      when:
        - not controller_subscription_installed | bool
