- name: Display credentials
  hosts: localhost
  gather_facts: no
  vars:
    gitea_username: developer
    gitea_namespace: gitea
  tasks:
    # Gitea data
    - name: Query developer password
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: gitea-developer-password
        namespace: "{{ gitea_namespace }}"
      register: gitea_developer_password_secret

    - name: Display gitea-developer-password secret
      ansible.builtin.debug:
        msg: "{{ gitea_developer_password_secret }}"
        verbosity: 2

    - name: Set fact for developer password
      ansible.builtin.set_fact:
        gitea_developer_password: "{{ gitea_developer_password_secret.resources[0].data.password | b64decode }}"

    - name: Get Gitea URL from OpenShift
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: gitea-https
        namespace: "{{ gitea_namespace }}"
      register: gitea_route

    - name: Create fact for the Gitea URL
      ansible.builtin.set_fact:
        gitea_url: "https://{{ gitea_route.resources[0].spec.host }}"

    # AAP data
    - name: Query AAP admin password
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: ctrl-admin-password
        namespace: ansible-automation-platform
      register: aap_admin_password_secret

    - name: Display aap-admin-password secret
      ansible.builtin.debug:
        msg: "{{ aap_admin_password_secret }}"
        verbosity: 2

    - name: Set fact for AAP admin password
      ansible.builtin.set_fact:
        controller_password: "{{ aap_admin_password_secret.resources[0].data.password | b64decode }}"

    - name: Get Automation Platform URL from OpenShift
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: ctrl
        namespace: ansible-automation-platform
      register: controller_route

    - name: Create fact for the route URL
      ansible.builtin.set_fact:
        controller_url: "https://{{ controller_route.resources[0].spec.host }}"

    # Print data
    - name: Print gitea user credentials if newly registered
      ansible.builtin.debug:
        msg:
          - "Gitea user: {{ gitea_username }}"
          - "Gitea password: {{ gitea_developer_password }}"
          # - "Gitea token: {{ gitea_developer_token }}"
          - "Gitea URL: {{ gitea_url }}"

    - name: Print Ansible Controller information
      ansible.builtin.debug:
        msg:
        - "Ansible Controller user    : admin"
        - "Ansible Controller password: {{ controller_password }}"
        - "Ansible Controller URL     : {{ controller_url }}"
        # - "Ansible Controller Token   : {{ controller_oauthtoken | default('Undefined: add a subscription') }}"
      when:
        - controller_url is defined
